# Configuration for the AI Agent System

project_name: "HelpMe"
author: "Aditya S Rathore"

# LLM Configuration
llm_providers:
    - name: "gemini"
      api_key_env: "GEMINI_API_KEY"
      models:
          - "gemini-1.5-flash"
    - name: "openrouter"
      api_key_env: "OPENROUTER_API_KEY"
      models:
          - "deepseek/deepseek-chat-v3.1:free"
          - "mistralai/devstral-small-2505:free"
          - "google/gemma-3n-e2b-it:free"
          - "meta-llama/llama-3.3-8b-instruct:free"
          - "x-ai/grok-4-fast:free"

# Default provider and model to use
default_provider: "openrouter"
default_model: "deepseek/deepseek-chat-v3.1:free"

# Choose the search tool for the Researcher Agent.
# Options: "duckduckgo" or "google"
search_tool: "duckduckgo"

# Specify the prompt files for the agents
researcher_prompt: "backend/app/prompts/researcher_system.txt"
synthesizer_prompt: "backend/app/prompts/synthesizer_system.txt"
query_rewriter_prompt: "backend/app/prompts/query_rewriter_system.txt"
