# Configuration for the AI Agent System

project_name: "HelpMe"
author: "Aditya S Rathore"

# Choose the LLM provider.
# Options: "gemini" or "openrouter"
llm_provider: "openrouter"

# Specify the models for each provider.
gemini_model: "gemini-1.5-flash"
# Free model options: 
# "deepseek/deepseek-chat-v3.1:free"
# "openai/gpt-oss-120b:free" 
# "google/gemma-7b-it:free"
# "microsoft/phi-2:free"
# "mistralai/mistral-7b-instruct:free"
openrouter_model: "deepseek/deepseek-chat-v3.1:free"


# Choose the search tool for the Researcher Agent.
# Options: "duckduckgo" or "google"
search_tool: "duckduckgo"

# Specify the prompt files for the agents
researcher_prompt: "backend/app/prompts/researcher_system.txt"
synthesizer_prompt: "backend/app/prompts/synthesizer_system.txt"
